version: "3.9"
services:
  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 33060:3306

  ftp_server:
    image: stilliard/pure-ftpd
    container_name: ftp_server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ftp-store:/home/ftpusers

    environment:
      - PUBLICHOST=ftp_server
      - FTP_USER_NAME=ftp_user
      - FTP_USER_PASS=ftp_password
      - FTP_USER_HOME=/home/ftpusers

volumes:
  db-store:
    driver: local

  ftp-store:
    driver: local
